### ISSUE TITLE
Navingating buttons on jobs per node don't work properly

### ISSUE THREAD

**Issue by Istatkov** [lukeskinner/OTHub#31]
1. Open My nodes
2. Select the node
3. Go to the Jobs section
4. Click next page of jobs won -> instead of listing next page, moves 1-2 jobs below. Maximum number of all pages shows as 8 ,but when you go to last page, it is just 8-10 jobs away from the top. 
5. If you filter by Start -> you can see the oldest jobs, but again you can scroll 8-10 jobs away through the buttons.
6. Same issue is observed on the sections below (i.e. Payouts for jobs)

**Comment by lukeskinner** [comment]
Now fixed across all pages - I went through each grid to confirm. Thanks for the report!
