### ISSUE TITLE
Cannot delete a node from "My nodes" section

### ISSUE THREAD

**Issue by Istatkov** [lukeskinner/OTHub#36]
I added a node to My nodes, but when I try to delete it, I get a popup message, which I confirm, and the node is still present in my list.

**Comment by lukeskinner** [comment]
I did a quick test in Chrome (85) and in Microsoft Edge (44) and I haven't been able to reproduce this yet. I can add and remove data holders with no issues.

I need to check some more browsers (Firefox, mobile etc) but I'm not sure why that's happening for you at the moment.

**Comment by lukeskinner** [comment]
Fixed in new website.
