### ISSUE TITLE
Home screen redesign / change of information displayed

### ISSUE THREAD

**Issue by lukeskinner** [lukeskinner/OTHub#7]
There are lots of statistics shown on the homepage which could be better focused on areas users want to see. 

If anyone has any thoughts feel free to comment on what you might like to see on the homepage.

**Comment by tschut** [comment]
It would be nice if the current graph with "Active offers" and "New offers" would be split in two or have to separate axes. It's currently very hard to see the amount of new offers because active is so much more.

**Comment by lukeskinner** [comment]
I think this can be improved upon further but I think it's good enough for v1.
